### ISSUE TITLE
How to use it with zabbix it services?

### ISSUE THREAD

**Issue by Oussamaabjx** [NovatecConsulting/novatec-service-dependency-graph-panel#126]
Hello , 
I contact you about your plugin Grafana Service dependency Graph , because I found some difficulties to connect  it with Zabbix and read data from it. Can someone give me a hint ? Thank you

**Comment by tobiangerstein** [comment]
Hi @Oussamaabjx Happy to hear that you are trying to use the SDG panel :) 

In order to be able to use the data, it is necessary to transform the data as such, that you provide a table formatted input as follows: https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel#use-your-own-data-source



source | target |metric
-- | -- | --
service a | service b | 50
service a | service c | 75
service c | service d | 25

In the config of the panel, you then can later configure, which column is your source column and which column is your target column :)
