### ISSUE TITLE
[BUG] - *Release ZIP has old path .../assets/service_icons included*

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [NovatecConsulting/novatec-service-dependency-graph-panel#70]
**Describe the bug**
In the release Zip-File there are the OLD icon-path ".../assets/service_incons/..." with the file "icon_index.json" included.
There are duplicate Files for  the external icons in the "..../assets/" Folder.

Both could be excluded. Only the files under "..../assets/icons/..." are needed any more.

**To Reproduce**
Unzip the release File and look at the folder

**Expected behavior**
Only the needed files under ".../assets/icons/.." are included.

**Screenshots**

**Your Setup:**
- OS Grafana is running on: SLES 15
- OS & Browser from which Grafana is accessed: Chrome (latest)
- Plugin-Version: 4.0.2
- Grafana-Version: 7.x
- Datasource & Version:
- Other: 

**Additional context**

**Comment by MariusBrill** [comment]
Hi @SaschaBrechmannVHV ,
please excuse the inconveniences! 

We have looked into the issue and figured that the old icon paths are present because an old dist folder was not deleted before building the release. To ensure that this will not happen again, we have implemented an automated release process. We have also updated the current release 4.0.2. 

Greetings
Marius
