### ISSUE TITLE
[BUG] - Wrong documentation, cannot set example

### ISSUE THREAD

**Issue by jbrepogmailcom** [NovatecConsulting/novatec-service-dependency-graph-panel#79]
Please provide as much and as detailed information as possible as it will make it easier for us to reproduce and fix the bug!

**Describe the bug**
The documentation at https://grafana.com/grafana/plugins/novatec-sdg-panel/ instructs that "aggregationType template variable is provided and set to app" and as such it is displayed at config image. However, when setting the example in grafana there is no aggregationType field and grafana gives error "Please provide a 'aggregationType' template variable.":

![image](https://user-images.githubusercontent.com/17232670/111377894-7e321480-86a1-11eb-9773-9f4a719b1aa6.png)

![image](https://user-images.githubusercontent.com/17232670/111377972-9144e480-86a1-11eb-8820-ab631b340b36.png)

Please update the page so it can be used to create working example. It is the only source how to learn to use your plugin. Thank you.

**To Reproduce**
A clear and concise description of how to reproduce the bug.

**Expected behavior**

**Screenshots**

**Your Setup:**
- OS Grafana is running on: Ubuntu
- OS & Browser from which Grafana is accessed: Chrome
- Plugin-Version: 2.3.0
- Grafana-Version: Grafana CLI version 7.0.0
- Datasource & Version: Google sheet
- Other: 

**Additional context**

**Comment by MariusBrill** [comment]
Hi @jbrepogmailcom,

The documentation is correct for the latest version of the panel. This version is not yet released in the marketplace of grafana. Unfortunately we can't do anything about this, since we need to wait for grafana to promote the latest version to the marketplace which apparently takes time.

If you want to keep using the version currently available on the marketplace use this [documentation](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/tree/v3.0.0).

Greetings
Marius
